server:
  port: ${SERVER_PORT:8075}

spring:
  application:
    name: authentication-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://localhost:8761/eureka/}

jwt:
  config:
    expirationTime: 3600000
    secret: 3bJAp`]4|kzB?~8+
